name: Build AMI
on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build_ami:

    # runner
    runs-on: ubuntu-latest

    steps:
    
      # checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2
      
      # build ami using packer
    - name: Build AMI
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        SUBNET_ID: ${{ secrets.SUBNET_ID }}
        PROD_ACCOUNT_ID: ${{ secrets.PROD_ACCOUNT_ID }}
      run: packer build ami.json