name: Validate AMI

on:
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  validate_ami:

    # runner
    runs-on: ubuntu-latest

    steps:
    
      # checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2
      
      # validate ami template
    - name: Validate AMI
      run: packer validate ami.json
